// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soapApi.Data;

namespace soapApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("soapApi.Models.FriendRequest", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("ReceiverId")
                        .IsRequired();

                    b.Property<string>("SenderId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendRequest");
                });

            modelBuilder.Entity("soapApi.Models.FriendShip", b =>
                {
                    b.Property<string>("FriendOneId");

                    b.Property<string>("FriendTwoId");

                    b.Property<DateTime>("FriendsSince");

                    b.Property<bool>("IsFriends");

                    b.HasKey("FriendOneId", "FriendTwoId");

                    b.HasIndex("FriendTwoId");

                    b.ToTable("FriendShip");
                });

            modelBuilder.Entity("soapApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("soapApi.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("soapApi.Models.FriendRequest", b =>
                {
                    b.HasOne("soapApi.Models.User", "Receiver")
                        .WithMany("OthersRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("soapApi.Models.User", "Sender")
                        .WithMany("MyRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("soapApi.Models.FriendShip", b =>
                {
                    b.HasOne("soapApi.Models.User", "FriendOne")
                        .WithMany("FriendsOne")
                        .HasForeignKey("FriendOneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("soapApi.Models.User", "FriendTwo")
                        .WithMany("FriendsTwo")
                        .HasForeignKey("FriendTwoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
